---
# Версия MongoDB Exporter
mongodb_exporter_version: "0.40.0"

# Версия Node Exporter
node_exporter_version: "1.8.1"

# Порты для прослушивания
mongodb_exporter_port: 9216
node_exporter_port: 50420

# Пользователь MongoDB для мониторинга
mongodb_exporter_user: "grafana"

# Пароль пользователя (должен быть переопределен)
mongodb_exporter_password: ""

# URI подключения к MongoDB
mongodb_uri: "mongodb://{{ mongodb_exporter_user }}:{{ mongodb_exporter_password }}@localhost:27017/?authSource=admin&tls=false"

# Дополнительные флаги экспортера
mongodb_exporter_flags:
  - "--collector.diagnosticdata"
  - "--collector.replicasetstatus"
  - "--collector.dbstats"
  - "--collector.dbstatsfreestorage"
  - "--collector.topmetrics"
  - "--collector.currentopmetrics"
  - "--collector.indexstats"
  - "--collector.collstats"
  - "--collector.profile"
  - "--discovering-mode"
  - "--compatible-mode"
