apiVersion: apps/v1
kind: Deployment
metadata:
  name: librespeed
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: librespeed
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: librespeed
    spec:
      imagePullSecrets:
      - name: registrysecret
      containers:
      - name: speedtest
        image: registry.rebrainme.com/workshops/middle/kubernetes-local/newplatform_autochecks/speedtest:5.3
        envFrom:
        - configMapRef:
            name: librespeed-env
        - secretRef:
            name: librespeed-secret
        volumeMounts:
        - name: config
          mountPath: /servers.json
          subPath: servers.json
      volumes:
      - name: config
        configMap:
          name: librespeed-servers.servers.json
---
apiVersion: v1
kind: Service
metadata:
  name: librespeed-svc
  namespace: final
  labels:
    app.kubernetes.io/instance: librespeed
spec:
  selector:
    app.kubernetes.io/instance: librespeed
  ports:
  - port: 80
    targetPort: 80