$ANSIBLE_VAULT;1.1;AES256
33396430656563323566303437636166353635356134343239363736656365343163663964643833
3463333066303661643939666361646138626235663439630a653630336238343336333535373032
38636133613036393530653831393631323939323865633962313234353734313538306134333432
3436643834396661660a626537393037363836363131393737323964656664376362626538393265
31336533633932613161646461656533663163666530616330323965383336643832366238666366
39623531653531626666353537613665376265393132303536373632366538376337353437666463
62633762313534396433373532633637393637323861666364343864313863613163663466346333
63303337393036346533
